import NavBar from "@/components/navbar/NavBar";
import "./globals.css";
import { Inter, Playfair_Display } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const playfair = Playfair_Display({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
